### PR TITLE
Update the mod to 1.19.4

### PR DESCRIPTION
**Pull request by TechPro424**
This PR updates the mod to 1.19.4

I was approached by a user on Discord named dreamcatcher#8788 to update the mod to 1.19.4, which I did
There aren't many changes, just migrated the mappings and updated the dependencies
It worked fine on my end, and I gave a build to dreamcatcher to test, they got back to me saying that everything worked fine.

I also specifically asked them to test if the issue mentioned by @Bstn1802 in https://github.com/Bstn1802/AutoReconnect/issues/38 occurs, and they told me that it does not, so the mod can probably be released to CurseForge without any changes.

I also updated the license in the fabric.mod.json to GPL-3.0, to match the license on the GH repo
On that note, you should probably take a look at https://github.com/Bstn1802/AutoReconnect/issues/42, as the GPL license is not advisable for Minecraft mods.

The only change that you might want to revert is https://github.com/Bstn1802/AutoReconnect/commit/c389e6295ef321b3d21520c9c6da43d91901bfe6, which I made because, for some reason, the variables were not resolving when I launched the game, and I got an error saying that the variables were invalid.

### CODE REVIEW

**Comment by cunhar** [comment]
@TechPro424 could i get a build of this latest working version to help test as well.

**Comment by TechPro424** [comment]
> @TechPro424 could i get a build of this latest working version to help test as well.

The mod jar is in the zip file
[autoreconnect-3.0.0-beta.zip](https://github.com/Bstn1802/AutoReconnect/files/11197801/autoreconnect-3.0.0-beta.zip)

**Comment by TechPro424** [comment]
@cunhar have you tested the mod?
And if yes, did you experience any issues?

**Comment by cunhar** [comment]
@TechPro424 it works great.  ive been using it on my server stream for over a month at this point and we've stayed connected the whole time.

**Comment by TechPro424** [comment]
This PR fixes #48

**Comment by xanulus** [comment]
Hey, very interested in getting this to work for 1.20 or 1.20.1. If there are any plans to update to the newer version it would be very much appreciated!

**Comment by TechPro424** [comment]
I'll work on updating this PR to 1.20

**Comment by TechPro424** [comment]
1.20 build: [autoreconnect-3.0.0-beta.zip](https://github.com/Bstn1802/AutoReconnect/files/11787282/autoreconnect-3.0.0-beta.zip)
Please test on both 1.20 and 1.20.1
the mod jar is inside the zip file

Let me know if there are any issues!
(Also, please test specifically if the issue mentioned by @Bstn1802 in https://github.com/Bstn1802/AutoReconnect/issues/38 occurs)

**Pull request closed without merging**
